services:
  elasticsearch:
    image: elasticsearch:9.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]
    networks: [internal]
    restart: unless-stopped

  kibana:
    image: kibana:9.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: ["5601:5601"]
    depends_on:
      elasticsearch:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5601/api/status"]
      interval: 5s
      timeout: 10s
      retries: 30
    networks: [internal]

  logstash:
    image: logstash:9.2.0
    ports: ["5044:5044"]
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    depends_on: [elasticsearch]
    networks: [internal]
    restart: unless-stopped

  kibana-init:
    image: curlimages/curl:8.10.1
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ./init.sh:/init.sh:ro
    networks: [internal]
    entrypoint: ["/bin/sh","-c"]
    command: ["/init.sh"]
    restart: "no"

networks:
  internal: {}
